### ISSUE TITLE
Put models folder into a new project named DataAccessSample from SwaggerODataSample solution

### ISSUE THREAD

**Issue by fusionshen** [Microsoft/aspnet-api-versioning#335]
Hi,

I have a bug in my demo when I use SwaggerODataSample(aspnetcore),and I do not know how to do with the DI of my new project DataAccessSample into startup.cs.

**### The log is:**
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNet.OData.TypeExtensions.<>c__DisplayClass23_0.<GetStructuredType>b__0(IEdmStructuredType t) in C:\Users\Fusionshen\Downloads\aspnet-api-versioning\src\Common.OData.ApiExplorer\AspNet.OData\TypeExtensions.cs:line 137
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.AspNet.OData.TypeExtensions.GetStructuredType(Type type, IEdmModel model, IEnumerable`1 assemblies) in C:\Users\Fusionshen\Downloads\aspnet-api-versioning\src\Common.OData.ApiExplorer\AspNet.OData\TypeExtensions.cs:line 137
   at Microsoft.AspNet.OData.TypeExtensions.SubstituteIfNecessary(Type type, IServiceProvider serviceProvider, IEnumerable`1 assemblies, ModelTypeBuilder modelTypeBuilder) in C:\Users\Fusionshen\Downloads\aspnet-api-versioning\src\Common.OData.ApiExplorer\AspNet.OData\TypeExtensions.cs:line 53
   at Microsoft.AspNetCore.Mvc.ApiExplorer.ODataApiDescriptionProvider.GetApiResponseTypes(IReadOnlyList`1 responseMetadataAttributes, Type responseType, IServiceProvider serviceProvider) in C:\Users\Fusionshen\Downloads\aspnet-api-versioning\src\Microsoft.AspNetCore.OData.Versioning.ApiExplorer\AspNetCore.Mvc.ApiExplorer\ODataApiDescriptionProvider.cs:line 556
   at Microsoft.AspNetCore.Mvc.ApiExplorer.ODataApiDescriptionProvider.<NewODataApiDescriptions>d__33.MoveNext() in C:\Users\Fusionshen\Downloads\aspnet-api-versioning\src\Microsoft.AspNetCore.OData.Versioning.ApiExplorer\AspNetCore.Mvc.ApiExplorer\ODataApiDescriptionProvider.cs:line 324
   at Microsoft.AspNetCore.Mvc.ApiExplorer.ODataApiDescriptionProvider.OnProvidersExecuted(ApiDescriptionProviderContext context) in C:\Users\Fusionshen\Downloads\aspnet-api-versioning\src\Microsoft.AspNetCore.OData.Versioning.ApiExplorer\AspNetCore.Mvc.ApiExplorer\ODataApiDescriptionProvider.cs:line 172
   at Microsoft.AspNetCore.Mvc.ApiExplorer.ApiDescriptionGroupCollectionProvider.GetCollection(ActionDescriptorCollection actionDescriptors)
   at Microsoft.AspNetCore.Mvc.ApiExplorer.ApiDescriptionGroupCollectionProvider.get_ApiDescriptionGroups()
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwagger(String documentName, String host, String basePath, String[] schemes)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
**### The bug location:**
![default](https://user-images.githubusercontent.com/8318221/44438989-4c916380-a5f4-11e8-8c13-bee70d44993a.png)

It seems that the DI of my new project DataAccessSample is not ok.

what can I do?

Regards

**Comment by Discjoggy** [comment]
I spend alot of time with **exactly the same exception** when I've tried to migrate a project to the beta release.
I ended up with removing all unnessecary Code and figured out that when I just have only one `ODataController` with a simple `Get` method it is fine (but swagger doesn't creates a good documentation, see following example), but when I use types I am getting exceptions.

Working:

```csharp
[ODataRoutePrefix("LibraryItems")]
[ApiVersion("1.0")]
public class LibraryItemsController : ODataController
{
    [Produces("application/json")]
    [ODataRoute]
    public IActionResult Get() => Ok(Repository.All.ToList());
}
```

Not working:

```csharp
[ODataRoutePrefix("LibraryItems")]
[ApiVersion("1.0")]
public class LibraryItemsController : ODataController
{
    [Produces("application/json")]
    [ProducesResponseType(typeof(ODataValue<IEnumerable<LibraryItem>>), 200)] // Exception !!
    [ODataRoute]
    public IActionResult Get() => Ok(Repository.All.ToList());
}
```

Startup:

```csharp
public void ConfigureServices(IServiceCollection services)
{
    services.AddMvc();
    services.AddApiVersioning(options => options.ReportApiVersions = true);
    services.AddOData().EnableApiVersioning();
    services.AddODataApiExplorer(options =>
    {
        options.GroupNameFormat = "'v'VVV"; // 'v'major[.minor][-status]
        options.SubstituteApiVersionInUrl = true;
    });

    services.AddSwaggerGen(options =>
    {
        var provider = services.BuildServiceProvider().GetRequiredService<IApiVersionDescriptionProvider>();
        foreach (var description in provider.ApiVersionDescriptions)
        {
            options.SwaggerDoc(description.GroupName, new Info { Version = description.ApiVersion.ToString() });
        }

        options.OperationFilter<SwaggerDefaultValues>();
        var xmlComments = Path.Combine(AppContext.BaseDirectory, $"{Assembly.GetEntryAssembly().GetName().Name}.xml");
        if (File.Exists(xmlComments))
        {
            options.IncludeXmlComments(xmlComments);
        }

        options.AddSecurityDefinition(
            "oauth2",
            new OAuth2Scheme
            {
                Type = "oauth2",
                Flow = "implicit",
                Description = "OAuth2.0 implicit flow",
                TokenUrl = configuration.GetValue("jwtIss", configuration["Jwt:Iss"]) + "/connect/token",
                AuthorizationUrl = configuration.GetValue("jwtIss", configuration["Jwt:Iss"]) + "/connect/authorize",
                Scopes = new Dictionary<string, string> { { "api1", "Access scope for " + ShortAssemblyName } }
            });
        options.AddSecurityRequirement(new Dictionary<string, IEnumerable<string>> { { "oauth2", new[] { "api1" } } });
    });
    // Some EF Core dependencies ..
}

public void Configure(IApplicationBuilder app, IApiVersionDescriptionProvider provider, VersionedODataModelBuilder modelBuilder)
{
    app.UseMvc(routeBuilder => routeBuilder.MapVersionedODataRoutes("odata", "api", modelBuilder.GetEdmModels()));
    app.UseSwagger();
    app.UseSwaggerUI(c =>
    {
        foreach (var description in provider.ApiVersionDescriptions)
        {
            c.SwaggerEndpoint($"/swagger/{description.GroupName}/swagger.json", description.GroupName.ToUpperInvariant());
        }
    });
}
```

I try to keep this Comment short so I can tell you more about missing `IModelConfiguration` etc. if needed.

**Comment by commonsensesoftware** [comment]
Sounds like this might be bug. Were either of you migrating from Web API? I can't help, but wonder if the same issue exists there. Much of the implementation source code is shared. If either of you have a simple repro you can share, it really helps me cut down on investigation time.

From what I'm seeing, it appears that the lookup for the specified response CLR type to the EDM type is failing. Behind the scenes, the API explorer will build a surrogate type for Swagger if, and only if, the current CLR type doesn't have 100% parity with the EDM type. This enables you to define a single model, but still yield a _filtered_ CLR type for Swagger based on the EDM. This is particularly useful since most model changes are additive.

Thanks for trying the beta and reporting this.

**Comment by Discjoggy** [comment]
Yes, we are currently working with OData 7.0.1 in an ASP.NET Core 2.1 App which is working as a Web API and it runs very well atm. It looks like the Swagger is taking care of the model configuration of Entity Framework Core too. Because when i tried to build a new simple web api project (without EF Core), the EDM-Gen told me to define a keys for the entities, furthermore there was no releations between entities.

We are using [Owned Types](https://docs.microsoft.com/de-de/ef/core/modeling/owned-entities), [Shadow Properties](https://docs.microsoft.com/de-de/ef/core/modeling/shadow-properties), [Global Query Filters](https://docs.microsoft.com/de-de/ef/core/querying/filters) and some navigration properties have circular references. I guess this can be a reason but our current project is a way too complex to reduce it to a simple example quicky, sorry.

Maybe @fusionshen agrees so we can try to look at this point in more detail. I'll keep trying to isolete the reason of this issue.

**Comment by fusionshen** [comment]
Thanks for your replies. @Discjoggy @commonsensesoftware 

I build a repo for the issue.[https://github.com/fusionshen/SwaggerODataSample](url)
the swaggerUI may crash, but url is ok.(http://localhost:5000/api/Orders)

**Comment by fusionshen** [comment]
Thanks for your replies. @Discjoggy @commonsensesoftware

I build a repo for the issue. https://github.com/fusionshen/SwaggerODataSample
the swaggerUI may crash, but url is ok.(http://localhost:5000/api/Orders)

**Comment by spasarto** [comment]
I was encountering the same issue, and found this workaround. In your Startup's Configure:

`applicationPartManager.ApplicationParts.Add(new` AssemblyPart(myAssembly));

This is because ODataApiDescriptionProvider uses the ApplicationPartManager to get the list of assemblies to scan for types.

(https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/app-parts?view=aspnetcore-2.1)

**Comment by commonsensesoftware** [comment]
Good point @spasarto. That _could_ be why it's not being automatically detected. If that's truly the issue, there are two ways to deal with it. Option 1 is exactly as @spasarto suggests. Option 2 is that you can add to the model builder **before** you build the models. Dependency Injection is a _convenience_ and not a requirement for things to work.

Either of the following are valid:

```c#
public void Configure( IApplicationBuilder app )
{
  var modelBuilder = new VersionedODataModelBuilder()
  {
      ModelConfigurations =
      {
          new PersonModelConfiguration()
      }
  };
  var models = modelBuilder.GetEdmModels();
  app.UseMvc( routes => routes.MapVersionedODataRoutes( "odata", default, models ) );
}
```
_Figure 1: Imperatively create a model builder without any Dependency Injection_

```c#
public void Configure( IApplicationBuilder app, VersionedODataModelBuilder modelBuilder )
{
  modelBuilder.ModelConfigurations.Add( new PersonModelConfiguration() );
  var models = modelBuilder.GetEdmModels();
  app.UseMvc( routes => routes.MapVersionedODataRoutes( "odata", default, models ) );
}
```
_Figure 2: Add to a model builder supplied via Dependency Injection_

**Comment by commonsensesoftware** [comment]
I've been able to confirm this is actually a bug that occurs in two parts:

1. When the model type is a different assembly it _may_ not be automatically added to the **AssemblyPartManager**, which is how assemblies are discovered by default
2. It is [falsely] assumed that a model type should be mapped to a CLR type from the available assemblies. This may not be true when part 1 is true, making the CLR type undiscoverable, and can actually result in a **NullReferenceException**.

I should have both of these issues fixed shortly and published in the next release.

In the meantime, you can work around the issue as @spasarto suggested or simply change line 27 in your example to:

```c#
services.AddMvc().AddApplicationPart(typeof(Order).Assembly);
```
