### ISSUE TITLE
InvalidOperationException: ValueFactory attempted to access the Value property of this instance.

### ISSUE THREAD

**Issue by icnocop** [Microsoft/aspnet-api-versioning#354]
Hi.

Thank you for ASP.NET API Versioning.

I get `System.InvalidOperationException: ValueFactory attempted to access the Value property of this instance.` when I try to add ASP.NET API Versioning to an existing ASP.NET web application that uses attribute routing.

The web application exposes two routes, `odata` and `api` with a `People` controller in each route that have different `Person` entities.

It works without issues before trying to add API versioning.

I've attached an example here:
[AttributeRoutingODataWebApiSample.zip](https://github.com/Microsoft/aspnet-api-versioning/files/2429817/AttributeRoutingODataWebApiSample.zip)

Steps to reproduce:
1. Extract contents of zip to `.\aspnet-api-versioning\samples\webapi\AttributeRoutingODataWebApiSample`.
2. Add project to `ApiVersioning.sln` in `samples\webapi` for example.
3. Set the solution configuration to `Debug | Any CPU`.
4. Set project as StartUp project.
5. Start Debugging.
6. Notice the exception `System.InvalidOperationException: 'ValueFactory attempted to access the Value property of this instance.'` with stack trace:
```
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Microsoft.Web.Http.Dispatcher.ApiVersionControllerSelector.GetControllerMapping()
   at System.Web.Http.Routing.AttributeRoutingMapper.AddRouteEntries(SubRouteCollection collector, HttpConfiguration configuration, IInlineConstraintResolver constraintResolver, IDirectRouteProvider directRouteProvider)
   at System.Web.Http.Routing.AttributeRoutingMapper.<>c__DisplayClass1_1.<MapAttributeRoutes>b__1()
   at System.Web.Http.Routing.RouteCollectionRoute.EnsureInitialized(Func`1 initializer)
   at System.Web.Http.Routing.AttributeRoutingMapper.<>c__DisplayClass1_0.<MapAttributeRoutes>b__0(HttpConfiguration config)
   at System.Web.Http.HttpConfiguration.ApplyControllerSettings(HttpControllerSettings settings, HttpConfiguration configuration)
   at System.Web.Http.Controllers.HttpControllerDescriptor.InvokeAttributesOnControllerType(HttpControllerDescriptor controllerDescriptor, Type type)
   at System.Web.Http.Controllers.HttpControllerDescriptor.InvokeAttributesOnControllerType(HttpControllerDescriptor controllerDescriptor, Type type)
   at System.Web.Http.Controllers.HttpControllerDescriptor..ctor(HttpConfiguration configuration, String controllerName, Type controllerType)
   at Microsoft.Web.Http.Dispatcher.ApiVersionControllerSelector.InitializeControllerInfoCache()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Microsoft.Web.Http.Dispatcher.ApiVersionControllerSelector.GetControllerMapping()
   at Microsoft.AspNet.OData.Builder.VersionedODataModelBuilder.GetApiVersions()
   at Microsoft.AspNet.OData.Builder.VersionedODataModelBuilder.GetEdmModels()
   at AttributeRoutingODataWebApiSample.App_Start.Startup.MapRoutesWithApiVersioning(HttpConfiguration configuration) in C:\github\icnocop\aspnet-api-versioning\samples\webapi\AttributeRoutingODataWebApiSample\App_Start\Startup.cs:72
   at AttributeRoutingODataWebApiSample.App_Start.Startup.Configuration(IAppBuilder app) in C:\github\icnocop\aspnet-api-versioning\samples\webapi\AttributeRoutingODataWebApiSample\App_Start\Startup.cs:20
```

You can see that it works without API versioning by commenting out `MapRoutesWithApiVersioning( configuration );` and then uncommenting `MapRoutes( configuration );` in `.\App_Start\Startup.cs`.

I expected the following GET requests to work:
http://localhost:2951/odata/People
http://localhost:2951/odata/People(1)
http://localhost:2951/api/People
http://localhost:2951/api/People('api')

Thank you.

**Comment by commonsensesoftware** [comment]
Ultimately, this is happening due to a recursion problem. I'm not sure where this is happening yet, but I've seen this behavior. This will require some investigation, but here's a few pointers to start with.

First, you should not call `configuration.EnsureInitialized()` directly. This will happen by the host when needed. The Web API and OData attribute mechanisms hook in and change this process. It's rare to need to call this directly. Second, I noticed that you're using two different **VersionedODataModelBuilder** instances, but I'm not sure why. I've never tried that. It's possible that is some how culprit.

It appears that you intend to mix OData and vanilla Web API controllers together. Your Web API controller, however, still has a bunch of OData stuff on it. In addition, the routing limitations in Web API will cause you grief if you use _direct routing_ (aka Attribute Routing) mixed with OData. API Versioning will **not** work if you mix this way for the same resource or route. Due to this restriction, I **strongly** recommend that you only use convention-based routing for this type of setup to retain your sanity.

If you haven't looked at it yet, you should review the [Advanced OData Sample](../tree/master/samples/webapi/AdvancedODataWebApiSample), which provides a working example of how to set everything up. Specifically, you want to look at the **Orders** controllers, which illustrates switching to and from OData across API versions.

That should be enough to get you started and perhaps even solve your issue. I'll carve out some time to review your repro as soon as I can. Thanks.

**Comment by icnocop** [comment]
Hi.

Thank you for the quick reply.

In the `AttributeRoutingODataWebApiSample.zip` sample project, I intended to create two OData endpoints; one in `/odata/` and another in `/api/`.

However, I also get the error when I try to use convention based routing for the `/odata/` OData endpoint but mix it with attribute routing for the `/api/` Web API endpoint.

I've attached a sample here:
[ConventionsODataAndAttributeWebApiSample.zip](https://github.com/Microsoft/aspnet-api-versioning/files/2430115/ConventionsODataAndAttributeWebApiSample.zip)

> API Versioning will **not** work if you mix this way for the same resource or route.

Does the `ConventionsODataAndAttributeWebApiSample.zip` sample project fall into this category?
The OData `PeopleController` uses a different model and route than the Web API `PeopleApiController`.

In the `ConventionsODataAndAttributeWebApiSample.zip` sample project, I expected the following GET requests to work:
http://localhost:2952/odata/People
http://localhost:2952/odata/People(1)
http://localhost:2952/api/People
http://localhost:2952/api/People/api

Thank you.

**Comment by commonsensesoftware** [comment]
There are a multitude of issues happening here. The example projects are meant to be more of an illustration of how to setup things up as opposed to something that you can copy and paste into a new solution. I'll consider creating project templates to ease this scenario in the future. I noticed that the original project references were still present, which means a lot of references were wrong.

In addition, I noticed that you tried to update the package versions to the latest versions. While that's not _wrong_, the general guidance is that you should only consider updating when you have a compelling reason to do so. The supported version of the OData versioning package does not support the OData 7.0+ version. The OData package notoriously introduces breaking changes. When you bump the major version this is allowed, so arguably it's on me to properly _clip off_ the higher versions. I'll make a point to update all the projects and packages to behave this way in the next release.

After looking things over, you are indeed trying to mix vanilla Web API routes with OData routes. In this scenario, I recommend that you only use convention-based routing. It's _possible_ to make attribute routing work in a limited capacity, but only for different controllers (e.g. resources). When mixing implementations between OData and non-OData, all controllers must use convention-based routing to function properly. For these reasons, I recommend only convention-based routing so you don't cross-eyed trying to debug your route configurations and resolutions.

The final issue has to do with the route prefixes. The design and support for mixing, versioned routes like this is for the same resource. By definition of the REST _Uniform Interface_ constraint, the URL path is the identifier of the resource. This means that the identifier (or URL path) to a person (e.g. `~/People`) should be consistent across API versions. What's different is the _representation_ of the resource. The API version functions in a similar way. It is a _discriminator_ for representation as opposed to a mapping to a method call. Although it's possible to have the `/odata` and `/api` prefixes, this seems confusing to me for the same resource (e.g. _People_); especially when combined with an API version. The resource is versioned, not the route prefix. If resources are split between the `/odata` or `/api` prefix, that makes some sense, although the `/odata` prefix is identifying a protocol and it's representation. This could be argued as a REST _anti-pattern_, since this should be handled by media type negotiation. The same is true of `/api` too, though it tends to be accepted as a discriminator when mixing hosting with UI resources.

Ultimately, I fear this type of configuration may be running up against what is possible in the routing infrastructure of Web API and OData. I'd like say part of the issue you're running into is, in fact, a bug because it seems like it _should_ work if you want it to (though I think it's a bit bizarre). I suspect this issue may still arise, even without OData, if routes with different prefixes for the same resource are used. If this was common scenario, I would have thought this would have been reported long ago. That doesn't mean it's not worth addressing - assuming it's even possible, but it would end up a lower priority. Intuition suggests this is not a particularly simple problem to solve.

All that being said, I've refined your solution with a number of fixes. The _happy_ path appears to behave exactly as expected. Exposing a resource on a single prefix appears to have more consistent results. I've included a new **Orders** resource to demonstrate that behavior. If you consolidate your prefixes all under `/api`, that will provide the most consistent behavior, which is how the _Advanced OData Example_ is setup.

Also note that you should **not** define an entity for an API version that you do not support. You elected to use `VersionedODataModelBuilder.DefaultModelConfiguration` to configure your models, but you didn't filter anything by API version. Since you only support a `1.0` _Person_ OData entity, you should only provide a configuration for that version. If you fail to do that, a resultant EDM entity will be generated and the OData libraries will believe that a matching controller should exist.

The repro is setup the way you had it, but if you switch things to all be under `/api`, you'll see things function as:

* `api/People?api-version=1.0` → 200 + application/json; odata.metadata=minimal
* `api/People(1)?api-version=1.0` → 200 + application/json; odata.metadata=minimal
* `api/People?api-version=2.0` → 200 + application/json
* `api/People/1?api-version=2.0` → 200 + application/json
* `api/People?api-version=3.0` → 400 (no such api version)
* `api/People/1?api-version=3.0` → 400 (no such api version)

[ConventionsODataAndAttributeWebApiSample.zip](https://github.com/Microsoft/aspnet-api-versioning/files/2431978/ConventionsODataAndAttributeWebApiSample.zip)

**Comment by icnocop** [comment]
Thank you for the detailed explanations.

It was my intention to have two resources, `/odata` and `/api`.

The `/odata` resource has already been deployed and being used by various consumers internally in our organization. A better name could have been `/private`.

The `/api` resource has also been deployed and being used by various consumers outside our organization. A better name could have been `/public`.

There are some identifers in `/api` that don't use conventional routing.

The different identifiers `/odata/People` and `/api/People` return different models and it works as expected like in my sample projects.

I'm trying to add versioning to both `/odata` and `/api` so they can be versioned independently.

- odata/People?api-version=1.0
`{ "@odata...", value: [ { "@odata...", PersonId: 1 } ] }`
- odata/People(1)?api-version=1.0
`{ "@odata...", PersonId: 1 }`
- api/People?api-version=1.0
` { "@odata...", value: [ { "@odata...", SocialSecurityNumber: "555-55-5555" } ] }`
- api/People('555-55-5555')?api-version=1.0
`{ "@odata...", SocialSecurityNumber: "555-55-5555" }`
- odata/People?api-version=2.0
`400 (no such api version)`
- api/People?api-version=2.0
`400 (no such api version)`

**Comment by commonsensesoftware** [comment]
This is definitely an _interesting_ scenario. Your approach might not be what _I_ would do, but it's not crazy.

I think we're up against what OData intrinsically supports. It's routing model is quite wonky. In particular, the OData path template overlaps a subset of the actual route template. Let me try to explain that in Laymen's terms.

You expect to the following routes to exist:
* `/odata/People`
* `/api/People`

From a pure Web API perspective, that's true and that's how the primary routing mechanisms work. **However**, this is not how the OData path template parsing and matching works. OData does not consider the _route prefix_ at all, which is also why the OData route registration is different, and arguably _weird_, compared to all other routes.

This is what OData actually sees:
* `/People`
* `/People`

This by itself wouldn't be a huge issue, but your expectation is that the _prefix_ results in different versioning _trees_, which is not the case. Due to OData's method of matching, the routing infrastructure sees all controllers as potential candidates. In fact, the filtering process considers any OData controller from the list of all possible controllers. Even the API version doesn't help disambiguate in this case because `/odata/People?api-version=1.0` and `/api/People?api-version=1.0` are expected to be different.

The **only** method thus far that I can think of to make this work is to add an additional discriminator to the filtering process - namely the prefix. You'd have to annotate this on all your controllers. It would look something like:

```c#
[ApiVerison("1.0")]
[RoutePrefix("odata")]
[ODataRoutePrefix("People")]
public class PeopleController : ODataController
{
}
```

The **RoutePrefixAttribute** doesn't mean anything to OData and has no side effects of its own (it has to be paired with **RouteAttribute**). This means it can be used to provide the metadata without creating a new attribute. This information can be used to match the controller defined in the route:

```c#
configuration.MapVersionedODataRoute(name: "odata", prefix: "odata", model);
```

It requires some changes in the library, but I believe that would work and get the result you're looking for.

A consequence of your setup is that reporting API versions will not work as expected - with or without this change. API versioning aggregates all the API versions of each resource. _Versioning trees_ are not supported. In other words, a _Person_ is a _Person_, but in your case you have essentially two different _Person_ resources that effectively mean different things albeit the main difference is attributes. The result is that API versioning will union all API versions for both trees, which _may_ not produce the expected result.

There are alternate ways to solve your problem as well.
1. Devise a versioning scheme that disambiguates _public_ from _private_. For example `x.0` (1.0) is always public and `x.5` (1.5) is always private. You could also use a status for private. Something like `1.0` is public and `1.0-private` is not. The prefix is irrelevant after that.
  a. It you're reporting API versions, you can't hide the private versions by default, but can replace the **IReportApiVersions** service to filter them out as necessary
2. Host `odata` and `api` as different web applications. I'm not sure how you're hosting, but you can use the `Host` HTTP header to host both applications on the same web server, but map them to separate, isolated applications. This will give the external appearance of a single application, when - in fact - they are segregated.
3. Use custom media type formatters or OData serializers/deserializers. This _might_ be more work than you're willing to do, but this is an approach that can use a single model and then handle payloads based on whether the request is _public_ or _private_. How you determine that is likely some type of authentication or authorization.

It's unfortunately tha OData matches this way, but I don't see another way around it - yet. If you want to continue on the path to try and filter by prefix, I can give it a shot, but know that reporting API versions _may_ break (if the two branches aren't symmetrical). I'm not sure there is a solution for that. Otherwise, one of the alternatives may prove to be easier, and certainly faster, to implement.

Let me know what you would like to do.

**Comment by icnocop** [comment]
Thank you for the clarification and explaining the limitations in OData's routing.

This explains some of the _weird_ things I've seen OData do.

For example, when the `GetPeople()` action in my `Api\PeopleApiController` is not implemented, OData uses the `OData\PeopleController` in order to process a `GET` request for `api/People`.

I'm curious as to what _you_ would choose/have chosen to do in this scenario.

I'm also planning to use Swagger/Swashbuckle for API documentation on both resources.

Each resource has its own security layer.

Thank you exploring the additional work-arounds.

I was thinking of implementing the alternating version for each resource like you mentioned, but as a last resort.

I would like to keep the web application as a single web application for maintainability reasons.

I'm currently already using an OData serializer for one of the entities in `/odata` but having an alternating version scheme seems more maintainable.

I'm wondering if there are plans to improve on the limitations in OData's routing in order to help resolve this issue? If the resolution is planned/implemented only for ASP.NET Core, it probably won't help me in the near term because our web application is currently running on ASP.NET 4.x.

I found these two issues that **may** be related to this issue:
https://github.com/OData/WebApi/issues/826
https://github.com/OData/WebApi/issues/1494

I would rather see the underlying issue fixed than implementing a work-around that may introduce its own limitations.

I'm currently required to decorate the controllers in at least one of my resources with `RoutePrefix` and `ODataRoutePrefix` in order for OData to route my HTTP requests correctly and differentiate between the same entity set name. I currently do that for the controllers in `Api` just because they're not as many as in `OData` currently.

The other thing I have to do is decorate at least one of my actions with `ODataRoute` and set the `RouteName` in order for OData to route my HTTP requests correctly and differentiate between the same entity type name. I currently do that for the actions in the controllers in `Api` for the same reason as indicated before.

Otherwise, in my case for example, OData tries to use `OData\PeopleController.GetPerson(long)` instead of `Api\PeopleApiController.GetPerson(string)` for a `GET` request on `api/Person('555-55-5555')` and fails with the error:
```
{
    "error": {
        "code": "",
        "message": "The request is invalid.",
        "innererror": {
            "message": "The parameters dictionary contains a null entry for parameter 'key' of non-nullable type 'System.Int64' for method 'System.Web.Http.IHttpActionResult GetPerson(Int64)' in 'AttributeRoutingODataWebApiSample.Controllers.OData.PeopleController'. An optional parameter must be a reference type, a nullable type, or be declared as an optional parameter.",
            "type": "",
            "stacktrace": ""
        }
    }
}
```

In my opinion, requiring attributes on just one of the conflicting/multiple resources would be an ideal requirement in resolving this issue and supporting this feature.

Having to create a custom service that implements `IReportApiVersions` is also an understandable requirement.

Thank you!

**Comment by commonsensesoftware** [comment]
I really can't say what else the OData team is considering to improve their routing semantics. Based on my observation of their track record, I don't expect improvements any time soon.

I thought about this quite a bit more. I'm pretty sure I _could_ make the routing match on prefix, but I'm fairly certain it would cause the API Explorer to not work correctly. At a minimum, it would be quite a lot of refactoring to make the API Explorer handle this type of scenario. This would be problematic for things like Swagger. You'd see the same resource/entity listed multiple times on different paths. Even if everything lined up, you'd still have some customization to do in order to bucketize between your two paths.

I understand why you're trying to do it this way, but it's arguably the antithesis of REST. Perhaps that isn't of utmost importance for your services, but I _try_ to use the constraints as guiding principles in the overall design.

That being said, your implementation is still supportable. Splitting your APIs by a prefix is only one way of many to address your challenge. Security _should_ be a cross-cutting concern. I would suggest coalescing down to a single prefix.  A _Person_ is a _Person_ no matter the route. This is really how an API version should be thought of too. The v1 and v2 of `/people/123` is still the same person, but just a different representation. This often why the only _true_ way to do API versioning is by media type negotiation.

OData definitely makes you have to jump through a few hoops, but you can _beat it into submission_. If your _secure_ entities are just subsets, then you need only allow the model to have optional members and strip them (e.g. _authorization_) before returning the results. It sounds like you only have two flavors of security: _public_ and _private_. If that's truly the case, you might be able to use entity inheritance as a way to do the filtering. The _public_ flavor would always get the filtered (e.g. base) entity and the _private_ flavor would get the extended entity containing additional, secure information. Yet another way would be using custom readers and writers that you plug in through dependency injection (ref: [here](http://odata.github.io/WebApi/#13-04-DependencyInjection) and [here](http://odata.github.io/odata.net/v7/#01-05-di-support)). I get the impression you might already be part way down that path, so incorporating the security bits may not be a huge leap.

Ultimately, I would bend OData to my will - somehow. I would probably start with one of the ways I just mentioned. The one thing I wouldn't do is split based on URL segment. Call me a _purist_, but a lot of thought went into the REST constraints, so I do what I can to abide by them.

It's not really an answer, but hopefully you find some of this useful and/or insightful.

**Comment by commonsensesoftware** [comment]
Did any of this help?

I did think of one more possible setup that might make this work. You _could_ create _nested_ applications using separate **HttpConfiguration** and **HttpServer** instances. Effectively, you can create a configuration and server with a  custom **HttpMessageHandler** that forwards to one nested application with one prefix and the other with the other prefix. Since the configurations are separate, that should allow them to be configured and setup separately. You should be able to reuse a lot of the setup code.

Seems like you _may_ have found a workable solution.

**Comment by icnocop** [comment]
Thank you for providing additional solutions to my scenario and your recommendations.

You've help a lot!

I'll have to re-consider my current approach and take your recommendations into account when I refactor my Web APIs in a subsequent iteration.

😃
