### ISSUE TITLE
SwaggerDefaultValues: What is wrong with this class definition?

### ISSUE THREAD

**Issue by rcanpahali** [Microsoft/aspnet-api-versioning#466]
I have created class like below. I have similar classes in my project, non of them causing error except this one. I can't find any problem in my class but it's causing exception, In my description variable, ModelMetadata property is null which is cause error.

This is how description variable is defined in my SwaggerDefaultValues.cs

`var description = context.ApiDescription.ParameterDescriptions.First(p => p.Name == parameter.Name);
`
And It throws exception here, ModelMetadata is null which is cause System.NullReferenceException:

`parameter.Description = description.ModelMetadata.Description;
`
As i trace my code, this class definition causes issue,

**CardPlusCNumberUpdateQueryParameter class:**

```
using System;
using System.ComponentModel.DataAnnotations;

namespace WestCore.AppCore.Services.PCsbins.Customer
{
    public class CardPlusCNumberUpdateQueryParameter
    {
        /// <summary>
        /// Customer Number
        /// </summary>
        [Range(1, 999999)]
        [Required]
        public int CustomerNumber { get; set; }


        /// <summary>
        /// CardPlus Customer Number
        /// </summary>
        [Required]
        public string CardPlusCustomerNumber { get; set; }
    }
}
```
**StackTrace:**

```
at WestCore.Api.Swagger.SwaggerDefaultValues.Apply(Operation operation, OperationFilterContext context) in C:\Users\can.pahali\source\WestCoreApiSS\Main\WestCore.Api\Swagger\SwaggerDefaultValues.cs:line 38
       at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.CreateOperation(ApiDescription apiDescription, ISchemaRegistry schemaRegistry)
       at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.CreatePathItem(IEnumerable`1 apiDescriptions, ISchemaRegistry schemaRegistry)
       at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.<>c__DisplayClass6_0.<CreatePathItems>b__2(IGrouping`2 group)
       at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
       at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
       at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.CreatePathItems(IEnumerable`1 apiDescriptions, ISchemaRegistry schemaRegistry)
       at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwagger(String documentName, String host, String basePath, String[] schemes)
       at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
```

**context.ApiDescription.ParameterDescriptions view:**  https://i.stack.imgur.com/WyqJI.png
**Throwen exception:** https://i.stack.imgur.com/P9nim.png

**Comment by commonsensesoftware** [comment]
I don't _think_ this is an issue with your model. According to the screenshot you provided, you have a route parameter called `{CustomerNumber}`, which does not have model metadata. Without seeing the route and action method, I can only speculate as to the issue. This usually means that the route parameter does match to an action method so the API Explorer doesn't know what the corresponding type is to build up its model metadata. There's two ways to fix this.

First, you can simply use the _null propagation_ operator which will yield a `null` description, but won't throw an exception:

```c#
parameter.Description = description.ModelMetadata?.Description;
```

The second way is to obviously fix your action method or wherever this parameter is coming from. I hope that helps.

**Comment by commonsensesoftware** [comment]
Did this help? Where you able to track down the issue?

**Comment by rcanpahali** [comment]
Yes It helped, but I'm still don't understand why ModelMetadata is null. Thank your for your answer.
