### ISSUE TITLE
Using CreatedAtActionResult result in routing error

### ISSUE THREAD

**Issue by ghorsey** [microsoft/aspnet-api-versioning#474]
I know this has been reported before, but I believe it may still be happening with the latest release.

I added the following controller to the `BasicSample` project for aspnet core:

```
namespace Microsoft.Examples.Controllers
{
    using Microsoft.AspNetCore.Mvc;

    [Route( "api/v{version:apiVersion}/[controller]" )]
    [ApiVersion( "1.0" )]
    [ApiController]
    public class Values3Controller : ControllerBase
    {
        [HttpGet( "{value}" )]
        public ActionResult<string> Get( string value ) => value;

        [HttpPost]
        public ActionResult Post()
        {
            return this.CreatedAtAction( nameof(this.Get), new { value = "string" }, "string" );
        }
    }
}

```

Running the Post endpoint:
```
POST http://localhost:5000/api/v1/values3 HTTP/1.1
Content-Type: application/json
cache-control: no-cache
Postman-Token: 2d13a6ef-cde3-47f0-8488-a7ae1327869d
User-Agent: PostmanRuntime/7.6.1
Accept: */*
Host: localhost:5000
accept-encoding: gzip, deflate
content-length: 0
Connection: keep-alive
```

Results in a 500 error response:
```
HTTP/1.1 500 Internal Server Error
Date: Tue, 12 Mar 2019 18:46:18 GMT
Server: Kestrel
Content-Length: 011
```

With a log from the console as:
```
Hosting environment: Development
Content root path: C:\code\learning\aspnet-api-versioning\samples\aspnetcore\BasicSample
Now listening on: https://localhost:5001
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLL73B7IKL2U", Request id "0HLL73B7IKL2U:00000001": An unhandled exception was thrown by the application.
System.InvalidOperationException: No route matches the supplied values.
   at Microsoft.AspNetCore.Mvc.CreatedAtActionResult.OnFormatting(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor.ExecuteAsync(ActionContext context, ObjectResult result)
   at Microsoft.AspNetCore.Mvc.ObjectResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

I know this has been reported before, and the workaround is to use the legacy routing:
`services.AddMvc( options => options.EnableEndpointRouting = false).SetCompatibilityVersion( Latest );`

But I thought I saw a merge request saying that the new routing should work with the latest 3.1 version.

**Comment by commonsensesoftware** [comment]
When you choose to version by URL path segment, the route parameter value is required. I _think_ there may be some scenarios where the routing system _auto-magically_ figures it out, but I'm not 100% sure what those are. Things are **guaranteed** to work if you supply all the route values.

The following should do the trick:

```c#
namespace Microsoft.Examples.Controllers
{
    using Microsoft.AspNetCore.Mvc;

    [Route( "api/v{version:apiVersion}/[controller]" )]
    [ApiVersion( "1.0" )]
    [ApiController]
    public class Values3Controller : ControllerBase
    {
        [HttpGet( "{value}" )]
        public ActionResult<string> Get( string value ) => value;

        [HttpPost]
        public ActionResult Post(ApiVersion apiVersion)
        {
            return this.CreatedAtAction( nameof(this.Get), new { value = "string", version = apiVersion.ToString() }, "string" );
        }
    }
}
```

This same setup can be seen in [this example](../blob/master/samples/aspnetcore/BasicSample/Controllers/HelloWorldController.cs). I hope that helps.

**Comment by ghorsey** [comment]
Makes sense... it used to be that the controller had the context of the current route values, so if there was a missing key from a response it would pull it from the current request route values.... So the incoming request had `apiResult` then in the response route it was optional when passing route values.

I would assume it still worked the same.  I will whack together a test and post results here to here to see if it works in 2.2 passing a "known" parameter value from a `POST` via a `CreatedAtAction` without mentioning it in the route values...  I'll post the conclusion here.

**Comment by commonsensesoftware** [comment]
@ghorsey were you able to come to a conclusion? I assume specifying the API version was sufficient to make things work as expected - yes?

**Comment by commonsensesoftware** [comment]
It seems that this issue was resolved. If that somehow is not the case, feel free to come back and/or reopen the issue. Thanks.
