### ISSUE TITLE
Method not found: 'Microsoft.AspNetCore.Mvc.Versioning.Conventions.ControllerApiVersionConventionBuilder

### ISSUE THREAD

**Issue by cilerler** [microsoft/aspnet-api-versioning#556]
Using **v4.0.0-preview8.19405.7**, and getting the error below right at `endpoints.MapControllers();`

```
System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'Microsoft.AspNetCore.Mvc.Versioning.Conventions.ControllerApiVersionConventionBuilder Microsoft.AspNetCore.Mvc.Versioning.Conventions.ApiVersionConventionBuilder.Controller(System.Type)'.
  Source=Microsoft.AspNetCore.OData.Versioning
  StackTrace:
   at Microsoft.AspNetCore.Mvc.Versioning.MetadataControllerConvention.Apply(ApplicationModel application)
   at Microsoft.AspNetCore.Mvc.Versioning.ODataApplicationModelProvider.OnProvidersExecuted(ApplicationModelProviderContext context)
   at Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModelFactory.CreateApplicationModel(IEnumerable`1 controllerTypes)
   at Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerActionDescriptorProvider.GetDescriptors()
   at Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerActionDescriptorProvider.OnProvidersExecuting(ActionDescriptorProviderContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.UpdateCollection()
   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.Initialize()
   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.GetChangeToken()
   at Microsoft.AspNetCore.Mvc.Routing.ActionEndpointDataSourceBase.<>c__DisplayClass11_0.<Subscribe>b__0()
   at Microsoft.Extensions.Primitives.ChangeToken.ChangeTokenRegistration`1..ctor(Func`1 changeTokenProducer, Action`1 changeTokenConsumer, TState state)
   at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
   at Microsoft.AspNetCore.Mvc.Routing.ActionEndpointDataSourceBase.Subscribe()
   at Microsoft.AspNetCore.Mvc.Routing.ControllerActionEndpointDataSource..ctor(IActionDescriptorCollectionProvider actions, ActionEndpointFactory endpointFactory)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Builder.ControllerEndpointRouteBuilderExtensions.GetOrCreateDataSource(IEndpointRouteBuilder endpoints)
   at Microsoft.AspNetCore.Builder.ControllerEndpointRouteBuilderExtensions.MapControllers(IEndpointRouteBuilder endpoints)
   at Brainiac.Api.Startup.<>c.<Configure>b__5_3(IEndpointRouteBuilder endpoints) in C:\Users\ciler\Source\github\smartprocure\brainiac\src\Brainiac.Api\Startup.cs:line 316
   at Microsoft.AspNetCore.Builder.EndpointRoutingApplicationBuilderExtensions.UseEndpoints(IApplicationBuilder builder, Action`1 configure)
   at Brainiac.Api.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env, IHostApplicationLifetime applicationLifetime, VersionedODataModelBuilder modelBuilder, IApiVersionDescriptionProvider provider) in C:\Users\ciler\Source\github\smartprocure\brainiac\src\Brainiac.Api\Startup.cs:line 283
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
```

**Comment by commonsensesoftware** [comment]
Based on the error, it's one or both of two things:

- You're attempting to use OData on .NET Core 3.0
- You're attempting to use _Endpoint Routing_

OData on ASP.NET Core does **not** support either of these. That also means OData currently cannot be used with ASP.NET Core 3.0. These limitations are out of my hands. I believe there are related, open issues in the OData repo. You may want to head over there.

API Versioning 4.0 (even in preview) multi-targets with ASP.NET 2.2 to provide new features and bug fixes to the OData implementation. If this is the scenario you're in, then the issue is likely because _Endpoint Routing_ is enabled (the new default). The sample applications show how to revert to the _legacy_ routing system for OData. If you're mixing and matching OData with non-OData controllers, I'm afraid you will have to use the _legacy_ routing system for everything. There can be only one.

I hope that helps

**Comment by cilerler** [comment]
@commonsensesoftware I appreciate.

You are right; I am attempting to use both of them. 😂 
I will follow it on OData, thanks again.

Thanks again.
