### ISSUE TITLE
Issue with OData Singleton entity controller actions

### ISSUE THREAD

**Issue by Graph2133** [microsoft/aspnet-api-versioning#610]
Hello, could you please help me. I'm trying to configure endpoint in OData controller which is configured as Singleton in my edm model. I'm reusing this sample https://github.com/microsoft/aspnet-api-versioning/tree/master/samples/aspnetcore/SwaggerODataSample (release 4.0 because it's crucial for real project which I'm working on). 
```
    public class PizzaConfiguration : IModelConfiguration
    {
        public void Apply(ODataModelBuilder builder, ApiVersion apiVersion)
        {
            builder.Singleton<Pizza>("Pizza");
            builder.EntityType<Pizza>().Select().Expand();
        }
    }
```
My controller has nothing extraordinary but just one simple action
```
    [ApiVersionNeutral]
    public class PizzaController : ODataController
    {
        [HttpGet]
        [Produces("application/json")]
        [EnableQuery(AllowedQueryOptions = AllowedQueryOptions.Select | 
             AllowedQueryOptions.Expand)]
        [ODataRoute("Pizza")]
        public SingleResult<Pizza> GetPizza(ODataQueryOptions<Pizza> options) 
            => SingleResult.Create(new[] { new Pizza { Name = "Test" } }.AsQueryable());
    }
```

But swashbuckle can not load api definitions and I'm getting this error:
```
System.Collections.Generic.KeyNotFoundException: The given key 'System.Reflection.TypeInfo' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Swashbuckle.AspNetCore.SwaggerGen.PrimitiveSchemaGenerator.GenerateSchemaFor(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.ChainableSchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.ArraySchemaGenerator.GenerateSchemaFor(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.ChainableSchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateParameter(ApiDescription apiDescription, ApiParameterDescription apiParameter, SchemaRepository schemaRepository)
   at System.Linq.Enumerable.WhereSelectListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperation(ApiDescription apiDescription, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperations(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GeneratePaths(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwagger(String documentName, String host, String basePath)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

If I remove ODataQueryOptions all works but I need them for proper generation of expansion properties because I want load only needed data to my singleton result using query options (checking whether needed expansion property was requested).
This works  with route "`api/pizza`" and swashbuckle generate proper schema:
```
    [ApiVersionNeutral]
    public class PizzaController : ODataController
    {
        [HttpGet]
        [Produces("application/json")]
        [EnableQuery(AllowedQueryOptions = AspNet.OData.Query.AllowedQueryOptions.Select | 
             AllowedQueryOptions.Expand)]
        [ODataRoute("Pizza")]
        public SingleResult<Pizza> GetPizza() 
            => SingleResult.Create(new[] { new Pizza { Name = "Test" } }.AsQueryable());
    }
```
And I've also question regarding generation of routes. Let's say iIve the same configuration I mentioned above but my controller will look like this (I will omit setting of ODataRoute and will use default routing convention)
```
    [ApiVersionNeutral]
    public class PizzaController : ODataController
    {
        [HttpGet]
        [Produces("application/json")]
        [EnableQuery(AllowedQueryOptions = AllowedQueryOptions.Select | 
            AllowedQueryOptions.Expand)]
        public SingleResult<Pizza> Get() 
            => SingleResult.Create(new[] { new Pizza { Name = "Test" } }.AsQueryable());
    }
```
Is it expected behavior that swagger action looks like this:

![image](https://user-images.githubusercontent.com/23173060/76913232-9c3d1d00-6873-11ea-86e0-1dcaa5d1afb6.png)

Shouldn't it be also `api/pizza` ?

**Comment by commonsensesoftware** [comment]
The first issue does **not** appear to be related to **ODataQueryOptions**. The issue is that there is no type information available. If you're not going to use `SingleResult<Pizza>`, then you need to use `[ProducesResponseType(typeof(Pizza), StatusCodes.Status200OK)]` or `[ProducesResponseType(typeof(ODataValue<Pizza>), StatusCodes.Status200OK)]`; otherwise, the API Explorer has no way to know what the model type is.

Reverse generation of route templates is difficult. There are no APIs that handle that. There are a number of complex OData routes. I'm not sure I have an example of a singleton. It's quite possible that scenario is broken. If the correct template is not being generated by convention, then the simplest workaround is to use attribute routing.

Do you have a repro you can share? Singleton route template generation _should_ be supported. If it's not working correctly, I take it as a bug once verified.

**Comment by Graph2133** [comment]
Oh, no I've tried with  ProducesResponseType attribute and the result is the same, for example this one will also result in error: 
```
    [ApiVersionNeutral]
    public class PizzaController : ODataController
    {
        [HttpGet]
        [Produces("application/json")]
        [EnableQuery(AllowedQueryOptions = AllowedQueryOptions.Filter | AllowedQueryOptions.Expand)]
        [ProducesResponseType(typeof(Pizza), StatusCodes.Status200OK)]
        [ODataRoute("Pizza")]
        public SingleResult<Pizza> GetPizza(ODataQueryOptions<Pizza> options) => SingleResult.Create(new[] { new Pizza { Name = "Test" } }.AsQueryable());
    }
```
```
System.Collections.Generic.KeyNotFoundException: The given key 'System.Reflection.TypeInfo' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Swashbuckle.AspNetCore.SwaggerGen.PrimitiveSchemaGenerator.GenerateSchemaFor(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.ChainableSchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.ArraySchemaGenerator.GenerateSchemaFor(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.ChainableSchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateParameter(ApiDescription apiDescription, ApiParameterDescription apiParameter, SchemaRepository schemaRepository)
   at System.Linq.Enumerable.WhereSelectListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperation(ApiDescription apiDescription, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperations(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GeneratePaths(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwagger(String documentName, String host, String basePath)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```
Sorry but no, I have no any prepared repository. I will need some time to prepare it.

**Comment by commonsensesoftware** [comment]
Hmmm ... interesting. While you're putting something together, I will attempt to investigate in parallel. Thanks.

**Comment by Graph2133** [comment]
Quickly configured version of repository:   https://github.com/Graph2133/ODataSingletonIssue

**Comment by pil0t** [comment]
Any news on this issue? Maybe an example of Singleton usage with Versioning?

**Comment by commonsensesoftware** [comment]
I'll categorize this as a bug since it's not what you expect ([POLA](https://en.wikipedia.org/wiki/Principle_of_least_astonishment)); however, it's more of an enhancement. It seems I just missed the case for _Singletons_. I've personally never used them, but they _should_ be supported if you want to use them.

The following top-level operations should be supported:

- [x] Entity sets
- [x] Operations (actions or functions + bounded or unbounded)
- [ ] Singletons

There's currently no consideration for singleton generation at all. There's several other issues related to API exploration and route template generation. This fix will roll up into those. I'll use the repro for the Litmus test. Thanks.

**Comment by commonsensesoftware** [comment]
Singletons are properly supported in [5.0.0-RC.1](https://www.nuget.org/packages/Microsoft.AspNetCore.OData.Versioning/5.0.0-rc.1). The official release will likely occur after 2 weeks of _burn-in_. The test suite and samples now include usage of singletons. If the issue returns, please reopen the issue or file a new one. Thanks.
