### ISSUE TITLE
CreatedAtAction fails to find correct route if action method postfixed with Async 

### ISSUE THREAD

**Issue by dnovhorodov** [microsoft/aspnet-api-versioning#656]
Greetings,

Using ASP.NET Core 3.1 web api project and `Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer` v4.1.1 package

Given following controller: 

```csharp
[Route("v{version:apiVersion}/[controller]")]
[ApiVersion("1.0")]
[ApiController]
public class ViewsController : BaseApiController
```

and action methods:
```csharp

[HttpGet("{viewId:int}")]
[ProducesResponseType(typeof(MessageLogViewModel), StatusCodes.Status200OK)]
[ProducesResponseType(StatusCodes.Status404NotFound)]
public async Task<IActionResult> GetViewByIdAsync(int viewId)
{
     return Ok(viewId)
}

[Route("create")]
[HttpPost]
[ProducesResponseType(StatusCodes.Status201Created)]
[ProducesResponseType(StatusCodes.Status400BadRequest)]
public async Task<IActionResult> CreateViewAsync([FromBody] CreateViewCommand createViewCommand, ApiVersion version)
{
    var id = await this.Mediator.Send(createViewCommand);
    return id > 0 ?
       this.CreatedAtAction(nameof(this.GetViewByIdAsync), new { viewId = id, version = version.ToString() }, null)
        : (IActionResult)this.BadRequest();
}
```

Following exception raised:

```
System.InvalidOperationException: No route matches the supplied values.
   at Microsoft.AspNetCore.Mvc.CreatedAtActionResult.OnFormatting(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor.ExecuteAsyncCore(ActionContext context, ObjectResult result, Type objectType, Object value)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor.ExecuteAsync(ActionContext context, ObjectResult result)
   at Microsoft.AspNetCore.Mvc.ObjectResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultAsync(IActionResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
```

### However if I rename _GetViewByIdAsync_ to _GetViewById_ everything works fine.

Additional info:

```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.302
 Commit:    41faccf259

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.302\

Host (useful for support):
  Version: 3.1.6
  Commit:  3acd9b0cd1
```

**Comment by commonsensesoftware** [comment]
Without testing it, but based on your example, I'm 99% sure this is caused by the known, breaking change: [Async suffix trimmed from controller action names](https://docs.microsoft.com/en-us/dotnet/core/compatibility/aspnetcore#mvc-async-suffix-trimmed-from-controller-action-names). It affects link generation. Everything else looks correct to me.

This has also been called out in #651, #601, and #558.

**Comment by commonsensesoftware** [comment]
Did this suggestion solve your issue?

**Comment by commonsensesoftware** [comment]
It seems this issue is resolved. If you _really_ want the `Async` suffix, you can also explicitly decorate actions with `[ActionName("...")]` or there is a MVC option to revert the behavior (but there be dragons). If you're still stuck, I'm happy to re-open the issue or elaborate further. Thanks.
