### ISSUE TITLE
SwaggerODataSample: V1 and V2 throw InvalidOperationException

### ISSUE THREAD

**Issue by StevenLiekens** [microsoft/aspnet-api-versioning#675]
Hi,

I'm checking out the 5.0.0-rc.1 package for OData and I noticed that V1 and V2 of the SwaggerODataSample don't work.

Here's the error message:

```
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:5000/swagger/v1/swagger.json
trce: Microsoft.AspNetCore.HostFiltering.HostFilteringMiddleware[2]
      All hosts are allowed.
dbug: Microsoft.AspNetCore.Routing.Matching.DfaMatcher[1000]
      No candidates found for the request path '/swagger/v1/swagger.json'
dbug: Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware[2]
      Request did not match any endpoints
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HM3HORVL1HTA", Request id "0HM3HORVL1HTA:00000001": An unhandled exception was thrown by the application.
System.InvalidOperationException: Can't use schemaId "$Order" for type "$Microsoft.Examples.Models.Order". The same schemaId is already used for type "$Microsoft.Examples.Models.Order"
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaRepository.ReserveIdFor(Type type, String schemaId)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaRepository.GetOrAdd(Type type, String schemaId, Func`1 factoryMethod)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGeneratorBase.GenerateSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.<>c__DisplayClass13_0.<GenerateRequestBodyFromBodyParameter>b__2(String contentType)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateRequestBodyFromBodyParameter(ApiDescription apiDescription, SchemaRepository schemaRepository, ApiParameterDescription bodyParameter)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateRequestBody(ApiDescription apiDescription, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperation(ApiDescription apiDescription, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperations(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GeneratePaths(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwagger(String documentName, String host, String basePath)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
dbug: Microsoft.AspNetCore.Server.Kestrel[9]
      Connection id "0HM3HORVL1HTA" completed keep alive response.
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 4.4282ms 500
```

**Comment by commonsensesoftware** [comment]
Thanks for trying things out. Coincidentally, I just happened to notice this yesterday (during a demo :S). Somehow I missed it during testing. I spot-checked the v3 and assumed all was good. EDM selection is now dynamic. When requested it ask the new **IEdmModelSelector** service to choose the right model. This is usually based on getting the API version from the current request. There is no request to get the API version from in API exploration. The selector can also choose the right model for a specifically requested API version, which exploration would know. If the selector cannot make a choice, it chooses the highest available version before allowing a NullReferenceException to occur. This results in v3 always being correct.

If the wrong model is selected, then a bunch of things fall down. Fortunately, this is a pretty simple fix. I just had to find the touch points. I'll work on getting out the ASAP.
